# R2DBC Configuration (Reactive Database Access)
spring.r2dbc.url=r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.max-idle-time=30m
spring.r2dbc.pool.max-acquire-time=3s

# JDBC Configuration (Keep for tools requiring JDBC like Liquibase)
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Disable JPA/Hibernate as R2DBC is used for the application logic
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never

server.port=${PORT:8080}
server.error.whitelabel.enabled=false
spring.jackson.serialization.fail-on-empty-beans=false

logging.level.root=INFO
logging.level.org.springframework.web=INFO
spring.jackson.serialization.write-dates-as-timestamps=false
